### ISSUE TITLE
点击运行，没反应，也没有任何报错！

### ISSUE THREAD

**Issue by cheng0009** [zypotato/go_spider_boss#1]
点击运行，没反应，也没有任何报错！也不知道哪里有问题

**Comment by zypotato** [comment]
看看是不是浏览器安装路径的问题   我刚刚更新了一版代码 可以安装最新的安装包再试试  以管理员身份启动程序  确保浏览器安装在这个路径C:\Program Files\Google\Chrome\Application\chrome.exe

**Comment by TaterTotX** [comment]
> 点击运行，没反应，也没有任何报错！也不知道哪里有问题

看看是不是浏览器安装路径的问题 我刚刚更新了一版代码 可以安装最新的安装包再试试 以管理员身份启动程序 确保浏览器安装在这个路径C:\Program Files\Google\Chrome\Application\chrome.exe
